In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler

from sklearn.feature_selection import SelectKBest, SelectPercentile
from sklearn.feature_selection import mutual_info_classif, chi2

from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

from sklearn.metrics import roc_auc_score, mean_squared_error

from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import CondensedNearestNeighbour

import category_encoders as ce

plt.style.use('seaborn-v0_8-colorblind')
%matplotlib inline

In [8]:
use_cols = ['Pclass', 'Sex', 'Age', 'Fare', 'SibSp', 'Survived']

data = pd.read_csv('data/titanic.csv', usecols=use_cols)
print(data.shape)
data.head(8)

(891, 6)

   Survived  Pclass     Sex   Age  SibSp     Fare
0         0       3    male  22.0      1   7.2500
1         1       1  female  38.0      1  71.2833
2         1       3  female  26.0      0   7.9250
3         1       1  female  35.0      1  53.1000
4         0       3    male  35.0      0   8.0500
5         0       3    male   NaN      0   8.4583
6         0       1    male  54.0      0  51.8625
7         0       3    male   2.0      3  21.0750

In [10]:
data['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Fare      891 non-null    float64
dtypes: float64(2), int64(3), object(1)
memory usage: 41.9+ KB

In [13]:
data.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Fare          0
dtype: int64

# Пропущенные значения

Проверка пропущенных значений

In [14]:
def check_missing(data, output_path=None):
    result = pd.concat([data.isnull().sum(), data.isnull().mean()], axis=1)
    result = result.rename(index=str, columns={0:'total missing', 1:'proportion'})
    if output_path is not None:
        result.to_csv(output_path+'missing.csv')
        print(output_path, 'missing.csv')
    return result

In [15]:
check_missing(data=data)

          total missing  proportion
Survived              0    0.000000
Pclass                0    0.000000
Sex                   0    0.000000
Age                 177    0.198653
SibSp                 0    0.000000
Fare                  0    0.000000

Удаление пропущенных значений

In [16]:
def drop_missing(data, axis=0):
    data_copy = data.copy(deep=True)
    data_copy = data_copy.dropna(axis=axis, inplace=False)
    return data_copy

In [18]:
data2 = drop_missing(data=data)
data2.shape

(714, 6)

Добавление переменной оценки пропущенных значений

In [19]:
def add_varr_denote_NA(data, NA_col=[]):
    data_copy = data.copy(deep=True)
    for i in NA_col:
        if data_copy[i].isnull().sum()>0:
            data_copy[i+'_is_NA'] = np.where(data_copy[i].isnull(),1,0)
        else:
            warn("Нет пропущенных значений" % i)
    return data_copy

In [20]:
data3 = add_varr_denote_NA(data=data, NA_col=['Age'])
print(data3.Age_is_NA.value_counts())
data3.head(8)

Age_is_NA
0    714
1    177
Name: count, dtype: int64

   Survived  Pclass     Sex   Age  SibSp     Fare  Age_is_NA
0         0       3    male  22.0      1   7.2500          0
1         1       1  female  38.0      1  71.2833          0
2         1       3  female  26.0      0   7.9250          0
3         1       1  female  35.0      1  53.1000          0
4         0       3    male  35.0      0   8.0500          0
5         0       3    male   NaN      0   8.4583          1
6         0       1    male  54.0      0  51.8625          0
7         0       3    male   2.0      3  21.0750          0

Заполнение пропусков выборочным значением

In [22]:
def impute_NA_with_arbitary(data, impute_value, NA_col= []):
    data_copy = data.copy(deep=True)
    for i in NA_col:
        if data_copy[i].isnull().sum()>0:
            data_copy[i+'_'+str(impute_value)] = data_copy[i].fillna(impute_value)
        else:
            warn("Нет пропузенных значений" % i)
    return data_copy

In [23]:
data4 = impute_NA_with_arbitary(data=data, impute_value=-999, NA_col=['Age'])
data4.head(8)

   Survived  Pclass     Sex   Age  SibSp     Fare  Age_-999
0         0       3    male  22.0      1   7.2500      22.0
1         1       1  female  38.0      1  71.2833      38.0
2         1       3  female  26.0      0   7.9250      26.0
3         1       1  female  35.0      1  53.1000      35.0
4         0       3    male  35.0      0   8.0500      35.0
5         0       3    male   NaN      0   8.4583    -999.0
6         0       1    male  54.0      0  51.8625      54.0
7         0       3    male   2.0      3  21.0750       2.0

Заполнение пропущенных значений средним/медианой/модой

In [24]:
def impute_NA_with_avg(data, strategy='mean', NA_col=[]):
    data_copy = data.copy(deep=True)
    for i in NA_col:
        if data_copy[i].isnull().sum()>0:
            if strategy=='mean':
                data_copy[i+'_impute_mean'] = data_copy[i].fillna(data[i].mean())
            elif strategy=='median':
                data_copy[i+'_impute_median'] = data_copy[i].fillna(data[i].median())
            elif strategy=='mode':
                data_copy[i+'_impute_mode'] = data_copy[i].fillna(data[i].mode()[0])
        else:
            warn("Нет пропущенных значений" % i)
    return data_copy

In [25]:
print(data.Age.median())
data5 = impute_NA_with_avg(data=data, strategy='median', NA_col=['Age'])
data5.head(8)

28.0

   Survived  Pclass     Sex   Age  SibSp     Fare  Age_impute_median
0         0       3    male  22.0      1   7.2500               22.0
1         1       1  female  38.0      1  71.2833               38.0
2         1       3  female  26.0      0   7.9250               26.0
3         1       1  female  35.0      1  53.1000               35.0
4         0       3    male  35.0      0   8.0500               35.0
5         0       3    male   NaN      0   8.4583               28.0
6         0       1    male  54.0      0  51.8625               54.0
7         0       3    male   2.0      3  21.0750                2.0